// Code generated by "stringer -type Kind --output kind_string.go"; DO NOT EDIT.

package tokenize

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Actions-2]
	_ = x[RunActionList-3]
	_ = x[CallActionList-4]
	_ = x[InvokeExternalBuff-5]
	_ = x[ActiveEnemies-6]
	_ = x[Time-7]
	_ = x[FightRemains-8]
	_ = x[Toggle-9]
	_ = x[SnapshotStats-10]
	_ = x[Rage-11]
	_ = x[Buff-12]
	_ = x[Debuff-13]
	_ = x[Cooldown-14]
	_ = x[Talent-15]
	_ = x[Target-16]
	_ = x[DOT-17]
	_ = x[RaidEvent-18]
	_ = x[Movement-19]
	_ = x[Equipped-20]
	_ = x[GCD-21]
	_ = x[Trinket-22]
	_ = x[If-23]
	_ = x[TargetIf-24]
	_ = x[Name-25]
	_ = x[VALUE-26]
	_ = x[Condition-27]
	_ = x[ValueElse-28]
	_ = x[Slot-29]
	_ = x[Op-30]
	_ = x[UseItem-31]
	_ = x[Variable-32]
	_ = x[Health-33]
	_ = x[Casting-34]
	_ = x[Proc-35]
	_ = x[Adds-36]
	_ = x[HasBuff-37]
	_ = x[HasStat-38]
	_ = x[Distance-39]
	_ = x[React-40]
	_ = x[Is-41]
	_ = x[AutoAttack-42]
	_ = x[Remains-43]
	_ = x[RemainsExpected-44]
	_ = x[Duration-45]
	_ = x[Stack-46]
	_ = x[Enabled-47]
	_ = x[Rank-48]
	_ = x[Ready-49]
	_ = x[Up-50]
	_ = x[Down-51]
	_ = x[Pct-52]
	_ = x[In-53]
	_ = x[Exists-54]
	_ = x[TTD-55]
	_ = x[CastTime-56]
	_ = x[HasUseBuff-57]
	_ = x[HasCooldown-58]
	_ = x[On-59]
	_ = x[Off-60]
	_ = x[SetIf-61]
	_ = x[AnyDPS-62]
	_ = x[Strength-63]
	_ = x[Trinket1-64]
	_ = x[Trinket2-65]
	_ = x[MainHand-66]
	_ = x[OffHand-67]
	_ = x[Min-68]
	_ = x[Floor-69]
	_ = x[Ceil-70]
	_ = x[Not-71]
	_ = x[LogicalOr-72]
	_ = x[LogicalAnd-73]
	_ = x[GE-74]
	_ = x[GT-75]
	_ = x[LE-76]
	_ = x[LT-77]
	_ = x[NE-78]
	_ = x[Mod-79]
	_ = x[Mult-80]
	_ = x[Div-81]
	_ = x[Add-82]
	_ = x[Sub-83]
	_ = x[Abs-84]
	_ = x[MathMax-85]
	_ = x[MathMin-86]
	_ = x[XOr-87]
	_ = x[Assign-88]
	_ = x[AddAssign-89]
	_ = x[ParenL-90]
	_ = x[ParenR-91]
	_ = x[Octothorpe-92]
	_ = x[Colon-93]
	_ = x[Comma-94]
	_ = x[Accessor-95]
	_ = x[Num-96]
	_ = x[ID-97]
}

const (
	_Kind_name_0 = "Invalid"
	_Kind_name_1 = "ActionsRunActionListCallActionListInvokeExternalBuffActiveEnemiesTimeFightRemainsToggleSnapshotStatsRageBuffDebuffCooldownTalentTargetDOTRaidEventMovementEquippedGCDTrinketIfTargetIfNameVALUEConditionValueElseSlotOpUseItemVariableHealthCastingProcAddsHasBuffHasStatDistanceReactIsAutoAttackRemainsRemainsExpectedDurationStackEnabledRankReadyUpDownPctInExistsTTDCastTimeHasUseBuffHasCooldownOnOffSetIfAnyDPSStrengthTrinket1Trinket2MainHandOffHandMinFloorCeilNotLogicalOrLogicalAndGEGTLELTNEModMultDivAddSubAbsMathMaxMathMinXOrAssignAddAssignParenLParenROctothorpeColonCommaAccessorNumID"
)

var (
	_Kind_index_1 = [...]uint16{0, 7, 20, 34, 52, 65, 69, 81, 87, 100, 104, 108, 114, 122, 128, 134, 137, 146, 154, 162, 165, 172, 174, 182, 186, 191, 200, 209, 213, 215, 222, 230, 236, 243, 247, 251, 258, 265, 273, 278, 280, 290, 297, 312, 320, 325, 332, 336, 341, 343, 347, 350, 352, 358, 361, 369, 379, 390, 392, 395, 400, 406, 414, 422, 430, 438, 445, 448, 453, 457, 460, 469, 479, 481, 483, 485, 487, 489, 492, 496, 499, 502, 505, 508, 515, 522, 525, 531, 540, 546, 552, 562, 567, 572, 580, 583, 585}
)

func (i Kind) String() string {
	switch {
	case i == 0:
		return _Kind_name_0
	case 2 <= i && i <= 97:
		i -= 2
		return _Kind_name_1[_Kind_index_1[i]:_Kind_index_1[i+1]]
	default:
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
